stages:
- stage: Build
  jobs:
  - job: Windows
    pool:
      name: Default
      demands:
      - agent.os -equals Windows_NT
    steps:
    - checkout: self
      submodules: true
    - script: python build/build.py azure . $(Build.BuildId) example
    - task: CopyFiles@2
      inputs:
        Contents: |
          products\example\example.log
          products\example\ExampleSetup.exe
        TargetFolder: $(Build.ArtifactStagingDirectory)
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: $(Build.ArtifactStagingDirectory)
        artifactName: Example
